### ISSUE TITLE
can't see the waveform on windows server 2012r2

### ISSUE THREAD

**Issue by MyNameIsMoney** [billkarsh/SpikeGLX#10]
Hi, Bill. I could run SpikeGLX well on windows10, but when I used it on windows server 2012r2, I could record data while I couldn't see the waveform on the GUI window, the whole window was black except the menu bar.

**Comment by billkarsh** [comment]
The SpikeGLX ‘System Requirements’ are visible on the code repo and the Downloads page. They differ slightly by SpikeGLX version but are always limited to desktop Windows versions like 7, 8.1, 10. That’s because the Qt framework underlying SpikeGLX is itself limited to desktop OS. The server OS versions contain somewhat different mixes of core support services, especially with respect to media and codecs. In this case, there is evidently some missing OpenGL component. I will close this issue if you are satisfied. Let me know.

**Comment by MyNameIsMoney** [comment]
Thank you very much for your help, I appreciate it. 


 
---Original---

**Comment by billkarsh** [comment]
Qt, hence SpikeGLX, only tested against desktop versions of Windows OS.
