### ISSUE TITLE
Question on behaviour markers

### ISSUE THREAD

**Issue by Qifan94** [billkarsh/SpikeGLX#12]
Hi. I am a junior PhD student and I am working on the neuropixels probes as well. 
For testing the behavior marker, I use two PCIe-6341 NI cards with BNC boxes. One is connected to Monkeylogic PC (a monkey task matlab packge) to send behaviour markers to the SpikeGLX recording PC. 

By using the Digital Input channel, I got signals like this.

![图片](https://user-images.githubusercontent.com/26030147/65386126-0b750100-dd6a-11e9-97c6-3ba142b41e39.png)

![图片](https://user-images.githubusercontent.com/26030147/65386159-6dce0180-dd6a-11e9-89ee-99160d4061fa.png)
Sorry for the bad quality of pictures.

The markers I used are ``111111`,`010010`, `001001` in sequnce.   But I recieved not only pulse signals but also some long square wave. So I wonder is there any mistake?

**Comment by Qifan94** [comment]
In other words, is there a strobe channel like other recording systems in SpikeGLX?

**Comment by billkarsh** [comment]
In SpikeGLX digital lines are recorded as the individual bits of the 16-bit XD words in each timepoint. I see in the settings you are recording digital lines 0:6, so these are the low 7 bits of a single 16-bit DX word in the NI stream. And in the screenshot of the graphs window you see 7 digital traces, but the waveforms look unfamiliar to you.

I don’t know how the marking codes work in Monkeylogic, nor do I know the term ‘strobe channel’. I have no idea how these signals are expected to look. However, SpikeGLX should be faithfully recording the signals that you have applied to the NI input terminals.

I recommend to break out the individual digital (TTL) signals and look at them on a scope at the same time to see if they are real. Look on the scope and SpikeGLX together because this might change the impedances, hence, the shapes. Let me know what that shows.
Bill

**Comment by Qifan94** [comment]
Hi, Bill.
Thanks a lot for your help.
I found I did a mistake of setting in MonkeyLogic. And I got the good event marker now.
