### ISSUE TITLE
Get a copy of the data stream

### ISSUE THREAD

**Issue by MarineChap** [billkarsh/SpikeGLX#18]
Hello ! 
I would like to know if there is an API to copy the datastream and send it over the network ? The matlab SDK can be used for this ? I would prefere to work with python, do you think it is possible ?
We would like to suppoort SpikeGLX (for neuropixels) on our new version of Falcon (real-time software)
Thank you

**Comment by billkarsh** [comment]
The MATLAB SDK provides a rich interface for driving SpikeGLX including fetching real-time data. Only one or two people use it, I think. I am putting your request for a Python interface on my agenda, though it is at the bottom of my list. I estimate I can get to it just about the time Python is abandoned for the next flash-in-the-pan language. C++ does it all, more efficiently than any other language, and it has been here since 1979. Why some people insist upon making junky imitator languages and why others happily leap toward them is entirely baffling to me. Sorry, it's not you. I've watched the art of programming slide mostly backward these forty years. Then again, life is mainly about personal expression, and finding one's way is always a random walk, isn't it? You see, it's best not to have such conversations in public fora...

I'd like to reserve the GitHub issues area for software bug reports. How-To questions like this are better handled as a direct question to me karshb@hhmi.org or even better, in the user community discussion forum here https://join.slack.com/t/neuropixelsgroup/shared_invite/enQtMzExMzEyMjg1MDE1LTg4NzJjZjIxNjA0M2YxNzBiNWRjOTc5MzMwZjgyMDk1ZmJiYzMxNTQyZGYwZmZlYjk1ODcwMTRmNWJiZGI3YjE.
-- Bill

**Comment by MarineChap** [comment]
Hello, Sorry for coming on the wrong channel. I will send you an email to continue the conversation.

I don't know how to formulate it but ... my mistake I was tired yesterday. Of course for real-time, I need a C++ lib not python (no idea why I wrote python to be honest). Falcon is written in C++ also.
