### ISSUE TITLE
IMEC openProbe(slot 2, port 1, dock 1) error 33 'port index 0 out of bound '.

### ISSUE THREAD

**Issue by juliencarponcy** [billkarsh/SpikeGLX#22]
Hello,

After successfully testing the probes with open ephys, I wanted to get started with SpikeGLX.
I have downloaded latest version and updated the firmware and restarted.
However, whatever the operation I try to make, e.g. test probes, synchronize niDaq and IMEC, I always have the same error:

IMEC openProbe(slot 2, port 1, dock 1) error 33 'port index 0 out of bound '.

Looks like a 0 based indexing error relating to probe port 1, but that maybe too obvious/simple to be true. I've tested with 2 different probes and get the same message.

Any idea?

Thanks for the work and for the reply a while ago regarding cable choice to link BNC2090A to PXI chassis..

Best,

Julien

**Comment by juliencarponcy** [comment]
I keep assuming that I was the one having it wrong so kept trying.
Actually, you should just precise that barely restarting the computer is not enough. 
You need the chassis to actually go off, which do not open when you do a mere restart because it kept being powered. 
I assume you should recommend to shut down the computer instead of restart, so the chassis really restart as well... that simple... sorry for posting before trying that, but maybe still helpful for others

Thanks

**Comment by billkarsh** [comment]
Great suggestion! I have rewritten the help to explicitly say the PC and chassis need to be shut down all the way. I'll also remind the community on slack. Thanks for helping.

**Comment by DaohanZhang** [comment]
The similar question. When I use HST mode to test my head-stage via the dongle, my SpikeGLX can find the right slot, but report ‘port index 0 out of bound ' when i set the port num to 1. If I set the port num to 2, it will report ‘port index 1 out of bound '. If i set 3 and 4, there will be similar questions. I have tried restart, shut down my PC as well as shut down the chassis, but the problem cannot be fixed.

**Comment by billkarsh** [comment]
I confirm that the port numbers (when no HST is present) are wrongly reported in the case that the module firmware is incorrect. The latest SpikeGLX tests for the correct firmware version on clicking 'Detect' in the Configure Run dialog, but this test is not applied for BIST or HST testing. What version of SpikeGLX do you have? Can you try 'Detect' on your system? What happens? Thanks.

**Comment by DaohanZhang** [comment]
![1](https://github.com/billkarsh/SpikeGLX/assets/73827050/e56744c9-111c-4303-b718-bd6543e80fa4)
![2](https://github.com/billkarsh/SpikeGLX/assets/73827050/852b87b7-5a32-46d8-8019-9b28a245beb2)
![3](https://github.com/billkarsh/SpikeGLX/assets/73827050/166f64a8-fa78-480d-9747-2c3252ab99f9)
My version is Release_v20230905-phase30 running on a win10 host PC
I have inserted my HST and dongle into the module, but the LED between USB connector do not turn green, the LED on the dongle and headstage do not light up.
I have tried detect, both with dongle and a probe connected to the headstage, but retrived the same error: 
  BS(slot 40)firmware version 0.0.0
  BSC(slot 40)part number simBSC
  (slot 40)serial number 0
  BSC(slot 40)hardware version 0.0
  BSC(slot 40)firmware version 0.0.0
  Probe bin file(slot 40,port 1,dock 1)missing .ap.bin'.
  FAI - Cannot be used
Is the problems of drivers I installed or there maybe some defects in cable, headstage and probe? Hope it is not the latter, since they are unused yet. Very Thanks!!!

**Comment by DaohanZhang** [comment]
[1](https://github.com/billkarsh/SpikeGLX/assets/73827050/9ff54b43-e64a-4b3c-91c2-6064b085bf17)
[3](https://github.com/billkarsh/SpikeGLX/assets/73827050/5e69ba6a-8e69-4aac-a834-04d4703a8546)
[2](https://github.com/billkarsh/SpikeGLX/assets/73827050/539d258d-e70c-4a90-841d-828f90c7dac6)
↑ There are some screenshots and photos, but they may not uploaded correctly due to some unknown web issues :(

**Comment by DaohanZhang** [comment]
Also note that in the photo showing dongle and chassis, the LED beside the port 4 is not light on, it is just light leaking from the above general LED. The picture of screen is taken when i connect cable to port 1. Anyway no matter which port i connect, i retrieved the same result: (slot 4, port [N], dock 1) HSTestXXXerror 'port index [N-1] out of bound '.  where N is 1,2,3 or 4

**Comment by billkarsh** [comment]
There are several issues to untangle. (1) You have configured slot #40 which is a totally simulated slot. That lets you run simulated probes even if you have no hardware. But let's first remove slot #40 using the 'Configure Slots' button and concentrate on getting the real hardware working. (2) The headstage tester is not very useful actually, because headstages are quite robust and are almost always just fine. Most importantly, the headstage tester can only be used with the headstage test dialog. (3) The strange errors you are getting in the headstage tests about port 0 are actually a clue that you do not have the correct module firmware loaded. (4) Unplug all headstage testers and probes and check a single box for your real module, say slot 4, port 1, dock 1. Now click 'Detect'. This should now report the actual module firmware versions. There will likely also be a message that you have the wrong version installed. (5) The correct firmware is in your SpikeGLX download, in the Firmware folder. Select 'Tools/Update Imec PXIe Firmware' and read the help text when you click the '?' button in the window title bar. That will explain how to get the firmware updated. (6) Let me know how it goes.
