### ISSUE TITLE
audio crash: firstsample

### ISSUE THREAD

**Issue by xingberlin** [billkarsh/SpikeGLX#29]
My SpikeGLX crashed and according to the instruction, I could rescue with typing in fileTimeSecs, fileSHA1, fileSizeBytes. However, The firstSample is also missing, and I need this information to do concatenation. How can I find the value for firstSample? 
Thanks a lot!!!

**Comment by billkarsh** [comment]
The firstSample metadata item is the index of the first sample recorded to the file; it can not be derived from other items. You'll have to manually inspect your data (perhaps the FileViewer can help) or use other things you know about experiment timing to approximate this missing item yourself.

As of version 20220101 I started writing the firstSample value into the metadata immediately on opening the file so this should not be lost during a crash unless you are using a rather old version.

The title of your issue is audio crash. In the FAQ list (download page) I mention that audio can cause a crash if accessing SpikeGLX remotely through RDP. There are tips to avoid that, or you can use Anydesk.

The next version coming soon has much improved audio signal-to-background for spikes, so you will want to get that when released. It will be version 20230425.

If you crashed because you ran out of disk space, remember there is a calculator on the Configure dialog Save tab to see how long you can safely run given your run parameters and remaining space.

Anything else I can help with?
