### ISSUE TITLE
Loading time 

### ISSUE THREAD

**Issue by jaymac640** [billkarsh/SpikeGLX#30]
SpikeGLX takes 10+ min to load when starting acquisition (with NIDAQ enabled).

**Comment by billkarsh** [comment]
It's not SpikeGLX: there's a large community of users running just fine for several years. You have something wrong with your computer, cards, NI drivers, or cables. What versions of Platform Services and DAQmx are installed? Also, what happens if you use NI-MAX to create and run a data acquisition task on your card? That will test a number of things without using SpikeGLX.

**Comment by billkarsh** [comment]
Please also tell me the list of NI hardware you have: Chassis model, link model, cards. What OS version do you have? When you open the NIMAX program and click the 'Devices and Interfaces' arrow, does the list display immediately or take a long time? Thanks, this will help us see if a particular combination of parts/software creates a conflict.

**Comment by jaymac640** [comment]
The issue was fixed, thank you!

**Comment by billkarsh** [comment]
For the benefit of others, can you say a few words about how this was fixed? Thanks in advance.

**Comment by jaymac640** [comment]
Updating the drivers fixed the issue.
