### ISSUE TITLE
error when disabling sync

### ISSUE THREAD

**Issue by panichem** [billkarsh/SpikeGLX#33]
Hi, 

I recently ran a calibration run, as described at:

file:///C:/SpikeGLX/Release_v20230411-phase30/SpikeGLX/_Help/SyncTab_Help.html

So, for my next [experimental] recording, I select 'disable sync waveform' in the sync tab, since, if I understand correctly, this is not longer necessary. However, I get the following error:

> Sync tab: IM PXI SMA input slot 2 is not enabled. 

Attaching a screenshot of the error, and also my hardware setup. 

Note that if I don't attempt to disable the sync signal, then no error is thrown. 

Any help understanding what is going on would be appreciated!

Thanks,
Matt

![error](https://github.com/billkarsh/SpikeGLX/assets/6961542/787467fc-0046-4af9-8e67-14222ebbf9df)
![hardware](https://github.com/billkarsh/SpikeGLX/assets/6961542/a0a201aa-d779-4a0a-8c6c-347fad56c969)

**Comment by billkarsh** [comment]
Hi Matt, hopefully these points will clear up confusion. (1) Doing a calibration run measures the true sample rates of the devices you selected for that calibration run. This will improve the accuracy of sync operations. You still want to do all your real runs (if multiple streams are enabled) with sync enabled; that just works better after having done the calibration run. (2) Whenever imec PXI modules are enabled they act as a group. Collectively, on the Sync tab, they are set to act as a sync source (one of them), or the group gets input (via one of them). When setting as a source, select one of them in the top box labeled 'Square wave source'. When the group is instead getting input, select one of them in the second 'Input' box. If not setting imec PXI as output, you ALWAYS have to select an enabled imec slot for input, EVEN if sync is disabled: that's because the SMA will record an extra TTL channel whether it represents sync or not, so you have to pick which active SMA. (3) You probably have an imec module in, say, slot 3, and you had selected it for output for an earlier run, like the calibration run. Because an imec slot is acting as output, the input spinner in the 'Input' box is not applicable, so has a default value of '2'. Next you disabled sync, so the Input spinner now must be set to a real imec slot. You just have to pick one of your enabled imec slots there.

**Comment by panichem** [comment]
Hi Bill, 

This was extremely clear and helpful, thanks so much. 

Matt
